include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
    - Static Analysis
    - Build
    - Test
    - Release
    - test
    - Deploy

checkstyle:
  stage: Static Analysis
  image: maven:3.8.3-jdk-11
  script:
    - mvn checkstyle:check

jacoco-check:
  stage: Static Analysis
  image: maven:3.8.3-jdk-11
  script:
    - mvn -Dspring.profiles.active=prod $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml

spring-test:
  stage: Test
  image: maven:3.8.3-jdk-11
  script:
    - mvn -Dspring.profiles.active=prod clean test

maven-build:
  stage: Build
  image: maven:3.8.3-jdk-11
  script:
    - mvn -Dspring.profiles.active=prod clean package -B
  artifacts:
    paths:
      - target/*.jar

release-image:
  stage: Release
  image: docker:20.10.7
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA"

deploy-ecs:
  stage: Deploy
  image: 'registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest'
  environment:
    name: production_notifications
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  script:
    - ecs update-task-definition
